name: LFS-warning

on:
  pull_request:
    types: [assigned, opened, edited, reopened, synchronize, ready_for_review]
  issue_comment:
    types: [created, edited]

jobs:
  lfs-warning:

    name: LFS Warning
    runs-on: ubuntu-latest

    steps:
      - name: LFS-warning
        uses: ActionsDesk/lfs-warning@v1.1
        with:
          # file size limit threshold
          filesizelimit: 1024 # default is 10485760
